################################################################################
#                                                                              #
# Example local config settings to customize this HPCTest installation.        #
# These override the builtin settings in                                       #
#       internal/src/config-data/config-builtin.yaml                           #
# Edit as needed.                                                              #
#                                                                              #
################################################################################
   

config:
  batch:
#-- default is 'manager: null', which runs jobs at the shell command line
#-- other 'batch' options are manager-dependent
#
#-- Slurm batch manager
#     manager: Slurm
#     params:
#       account:   myaccount
#       partition: mypartition
#       time:      "5:00"      # 5 min (time for Slurm given in seconds)
#
#-- Summit batch manager (custom version of LSF)
#     manager: Summit
#     params:
#       project:   myproject
#       time:      "0:05"      # 5 min (time for Summit given in minutes)
#     prelude: module unload darshan-runtime
#
#-- debugging options
#     debug:
#       force: True   # ignore executor's check for availability

build:
#  compiler:
#    gcc

run:
# ulimit:
#   t: unlimited  # cpu time (seconds)

profile:
# hpctoolkit: 
#   -- if no path is given, your PATH setting will be used
#   path: ~/hpctoolkit/INSTALL/
#    
#   -- profiling params to use when none are specified on hpctest command line
#   -- if none are given here, ("REALTIME@10000", "", "") will be used
#   hpcrun params:     ""
#   hpcstruct params:  ""  
#   hpcprof params:    ""  


-e PAPI_TOT_INS” and “-e PAPI_TOT_CYC
 
