#================================================#
# LULESH PACKAGE FILE TO BE GENERATED BY HPCTEST #
#================================================#


# from info.name, info.description, and build.kind
from spack import *
class Minife(MakefilePackage):
    """Many important simulation problems of interest to DOE involve complex multi-material
    systems that undergo large deformations. LULESH is a highly simplified application
    that represents the numerical algorithms, data motion, and programming style typical
    in scientific C or C++ based hydrodynamic applications. The Shock Hydrodynamics
    Challenge Problem was originally defined and implemented by LLNL as one of five
    challenge problems in the DARPA UHPC program and has since become a widely studied
    proxy application in DOE co-design efforts for exascale. It has been ported to a number
    of programming models and optimized for a number of advanced platforms. 
    """

# from info.homepage and info.url
    homepage = "https://mantevo.org/"
    url      = "https://github.com/HPCToolkit"

# from info.version
    version('2.0-rc3', 'app/miniFE')

# from config[2].{variant,description}, and config[0].'default variants'
    variant('openmp', description='Build with OpenMP support', default=True)

# from config[3].{variant,description,depends}, and config[0].'default variants'
    variant('mpi', description='Build with MPI support', default=True)
    depends_on('mpi', when='+mpi')

# boilerplate for config[*].flags...
    @property
    def build_targets(self):
        targets = []
        
## from config[@base].languages
##    languages: [ cxx ]
        languages = 'CXX = {}'.format(spack_cxx)
        
## from config[@base].flags
##      CXXFLAGS: "-g -O3"
        cxxflags = '-g -O3'
        ldflags = '-g -O3'
        
## from config[@openmp].flags
##      +CXXFLAGS: $OPENMP_FLAG
##      +LDFLAGS:  $OPENMP_FLAG
        if '+openmp' in self.spec:
            cxxflags += ' ' + self.compiler.openmp_flag
            ldflags  += ' ' + self.compiler.openmp_flag
        
## from config[@mpi].languages
##    languages: [ mpicxx ]
        if '+mpi' in self.spec:
            languages = 'CXX = {}'.format(self.spec['mpi'].mpicxx)
        
## from config[@mpi].flags
##    flags: +CXXFLAGS: "-DUSE_MPI=1"
        if '+mpi' in self.spec:
            cxxflags += ' ' + '-DUSE_MPI=1'
        
## from config[@mpi].env
##      - "MPI_INC = $MPI_INC"
##      - "MPI_LIB = $MPI_LIB"
        if '+mpi' in self.spec:
            targets.append('MPI_INC = {0}'.format(self.spec['mpi'].prefix.include))
            targets.append('MPI_LIB = {0}'.format(self.spec['mpi'].prefix.lib))

# boilerplate closing 'build_targets'
        targets.append(languages)
        targets.append('CXXFLAGS = {0}'.format(cxxflags))
        targets.append('LDFLAGS = {0}'.format(ldflags))
        return targets

# from build.dir
    def build_directory(self):
        return "src"

# from build.install
    def install(self, spec, prefix):
        mkdirp(prefix.bin)
        install('src/miniFE.x', prefix.bin)




